/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedPiecesRouteImport } from './routes/_authed/pieces'
import { Route as AuthedPracticesRouteImport } from './routes/_authed/practices'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminVenuesRouteImport } from './routes/_authed/admin/venues'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPiecesRoute = AuthedPiecesRouteImport.update({
  id: '/pieces',
  path: '/pieces',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPracticesRoute = AuthedPracticesRouteImport.update({
  id: '/practices',
  path: '/practices',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminVenuesRoute = AuthedAdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/pieces': typeof AuthedPiecesRoute
  '/practices': typeof AuthedPracticesRoute
  '/admin/venues': typeof AuthedAdminVenuesRoute
  '/admin/': typeof AuthedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pieces': typeof AuthedPiecesRoute
  '/practices': typeof AuthedPracticesRoute
  '/': typeof AuthedIndexRoute
  '/admin/venues': typeof AuthedAdminVenuesRoute
  '/admin': typeof AuthedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/pieces': typeof AuthedPiecesRoute
  '/_authed/practices': typeof AuthedPracticesRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/venues': typeof AuthedAdminVenuesRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/pieces'
    | '/practices'
    | '/admin/venues'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/pieces' | '/practices' | '/' | '/admin/venues' | '/admin'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/admin'
    | '/_authed/pieces'
    | '/_authed/practices'
    | '/_authed/'
    | '/_authed/admin/venues'
    | '/_authed/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/pieces': {
      id: '/_authed/pieces'
      path: '/pieces'
      fullPath: '/pieces'
      preLoaderRoute: typeof AuthedPiecesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/practices': {
      id: '/_authed/practices'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof AuthedPracticesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/venues': {
      id: '/_authed/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AuthedAdminVenuesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminVenuesRoute: typeof AuthedAdminVenuesRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminVenuesRoute: AuthedAdminVenuesRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedPiecesRoute: typeof AuthedPiecesRoute
  AuthedPracticesRoute: typeof AuthedPracticesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedPiecesRoute: AuthedPiecesRoute,
  AuthedPracticesRoute: AuthedPracticesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
